version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: yisu-mysql
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: yisu-adminer
    restart: always
    ports:
      - "8888:8080"

volumes:
  mysql_data:
